### ISSUE TITLE
configuration instructions

### ISSUE THREAD

**Issue by epcim** [jhoralek/acond-heat-pump#2]
@jhoralek Can you please provide some configuration/installation instructions/example.

Additional questions:
- is this still valid and working?
- does it works independently or only with HACS?
- the name of modbus integration is hardcoded as 'hub'?

**Comment by jhoralek** [comment]
Hi,
thanks for your interest.
This project is stopped at the moment.

I think id does not work right now, because of the braking changes in HACS and HA overall.

If you need to communicate with your acond heat pump, it is possible over modbus protocol. 
You can link it in HA.

In your configuration.yaml just use

```yaml

# # Acond TC
modbus:
  - type: tcp
    name: TC
    host: 192.168.2.8
    port: 502

```

chang host nad port. You can scan your network, find your heat pump. FING app for android is quit good to 
find devices in network and open port on each device.

More deap info can be find [here](https://www.home-assistant.io/integrations/modbus/)

**Comment by epcim** [comment]
Thanks, modbus integration is what i am already using. I was looking for some existing sensors configuration I could reuse.PMiOn 14 Jul 2022 09:58, Jiří Horálek ***@***.***> wrote:
Hi,
thanks for your interest.
This project is stopped at the moment.
I think id does not work right now, because of the braking changes in HACS and HA overall.
If you need to communicate with your acond heat pump, it is possible over modbus protocol.
You can link it in HA.
In your configuration.yaml just use
# # Acond TC
modbus:
  - type: tcp
    name: TC
    host: 192.168.2.8
    port: 502

chang host nad port. You can scan your network, find your heat pump. FING app for android is quit good to
find devices in network and open port on each device.
More deap info can be find here
